title: "Damon Ditrichs · CS 499 ePortfoli"
description: "Capstone portfolio demonstrating growth in computer science by showcasing enhancements in Software Design and Engineering , Algorithms and Data Structures, and Databases."
theme: jekyll-theme-cayman 
 
